### ISSUE TITLE
ex_open_par hangs when exodus is build with latest intel compilers

### ISSUE THREAD

**Issue by bourdin** [sandialabs/seacas#356]
When building exodus with the latest intel compilers (2022.2.0) and MPI (2021.7.0) on a RHEL7 box calls to `ex_open_par` hang when running on more than 1 CPU. 
For some reason I can't attach a .c file, but here is a minimalist test:
```
/*
 * Copyright(C) 1999-2021 National Technology & Engineering Solutions
 * of Sandia, LLC (NTESS).  Under the terms of Contract DE-NA0003525 with
 * NTESS, the U.S. Government retains certain rights in this software.
 *
 * See packages/seacas/LICENSE for details
 */

#include "exodusII.h"
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
  MPI_Comm mpi_comm = MPI_COMM_WORLD;
  MPI_Info mpi_info = MPI_INFO_NULL;
  float  version;
  int CPU_word_size = 0; /* sizeof(float) */
  int IO_word_size  = 0; /* use what is stored in file */

  ex_opts(EX_VERBOSE | EX_ABORT);

  /* Initialize MPI. */
  MPI_Init(&argc, &argv);

  /* open EXODUS II files */
  printf("\nbefore ex_open\n");
  int exoid = ex_open_par("test.exo",     /* filename path */
                          EX_READ,        /* access mode = READ */
                          &CPU_word_size, /* CPU word size */
                          &IO_word_size,  /* IO word size */
                          &version,       /* ExodusII library version */
                          mpi_comm, mpi_info);

  printf("\nafter ex_open\n");
  if (exoid < 0)
    exit(1);

  int error = ex_close(exoid);
  printf("\nafter ex_close, error = %3d\n", error);
  MPI_Finalize();
  return 0;
}
```

Attaching the debugger to the hanging code, I get the following backtrace:
```
(gdb) bt
#0  0x00007fb15da8793e in MPIDI_SHMGR_Gather_generic (opcode=1594247784, mpir_comm=0x7ffc2262b108, root=5, localbuf=0x0, sendbuf=0x7fb112b85280 <util_cq_ops>, 
    allreduce_netbuf=0x7ffc2262b0b0, count=1, datatype=1275069445, op=1476395009, errflag=0x7ffc22638878, knomial_factor=2, algo_type=MPIDI_SHMGR_ALGO_KNOMIAL)
    at ../../src/mpid/ch4/src/intel/ch4_shm_coll_templates.h:527
#1  0x00007fb15da8686a in MPIDI_SHMGR_Gather_reduce (comm=0x7fb15f064a68 <PVAR_TIMER_idle+8>, root=576893192, sendbuf=0x5, recvbuf=0x0, count=314069632, 
    dt=576893104, op=1476395009, errflag=0x7ffc22638878, algo=MPIDI_SHMGR_ALGO_KNARY, radix=1) at ../../src/mpid/ch4/src/intel/ch4_shm_coll.c:2670
#2  0x00007fb15d99f194 in MPIDI_POSIX_Allreduce_intra_gather_release (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, 
    datatype=<optimized out>, op=<optimized out>, comm=<optimized out>, errflag=<optimized out>, ch4_algo_parameters_container=<optimized out>)
    at ../../src/mpid/ch4/include/../shm/posix/intel/posix_coll_impl.h:274
#3  MPIDI_POSIX_mpi_allreduce (sendbuf=0x7fb15f064a68 <PVAR_TIMER_idle+8>, recvbuf=0x7ffc2262b108, count=5, datatype=0, op=314069632, comm_ptr=0x7ffc2262b0b0, 
    errflag=0x7ffc22638878, ch4_algo_parameters_ptr_in=0x7ffc2263897c) at ../../src/mpid/ch4/shm/posix/../src/../posix/intel/posix_coll.h:86
#4  0x00007fb15d9bd754 in MPIDI_SHM_mpi_allreduce (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, 
    op=<optimized out>, comm=<optimized out>, errflag=<optimized out>, algo_parameters_container=0x141)
    at ../../src/mpid/ch4/shm/posix/../src/intel/shm_coll.h:57
#5  MPIDI_Allreduce_intra_composition_gamma (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, 
    op=<optimized out>, comm_ptr=<optimized out>, errflag=<optimized out>, ch4_algo_parameters_container=<optimized out>)
    at ../../src/mpid/ch4/src/intel/ch4_coll_impl.h:825
#6  MPID_Allreduce_invoke (sendbuf=0x7ffc2263897c, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, op=<optimized out>, 
    comm=0x7fb15ebf8598 <MPIR_Comm_direct+2232>, errflag=0x7ffc22638878, ch4_algo_parameters_container=<optimized out>)
    at ../../src/mpid/ch4/src/intel/ch4_coll_select_utils.c:1812
#7  MPIDI_coll_invoke (coll_sig=0x7fb15f064a68 <PVAR_TIMER_idle+8>, container=0x7ffc2262b108, req=0x5)
    at ../../src/mpid/ch4/src/intel/ch4_coll_select_utils.c:3359
#8  0x00007fb15d995a80 in MPIDI_coll_select (coll_sig=0x7fb15f064a68 <PVAR_TIMER_idle+8>, req=0x7ffc2262b108)
    at ../../src/mpid/ch4/src/intel/ch4_coll_globals_default.c:143
#9  0x00007fb15da97737 in MPID_Allreduce (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, 
    op=<optimized out>, comm=<optimized out>, errflag=<optimized out>) at ../../src/mpid/ch4/src/intel/ch4_coll.h:77
#10 MPIR_Allreduce (sendbuf=0x7fb15f064a68 <PVAR_TIMER_idle+8>, recvbuf=0x7ffc2262b108, count=5, datatype=0, op=314069632, comm_ptr=0x7ffc2262b0b0, 
    errflag=0x7ffc22638878) at ../../src/mpi/coll/intel/src/coll_impl.c:265
#11 0x00007fb15d9411c0 in PMPI_Allreduce (sendbuf=0x7fb15f064a68 <PVAR_TIMER_idle+8>, recvbuf=0x7ffc2262b108, count=5, datatype=0, op=314069632, comm=576893104)
    at ../../src/mpi/coll/allreduce/allreduce.c:373
#12 0x00007fb15d8b3cbe in ADIO_Open (orig_comm=1594247784, comm=576893192, filename=0x5 <Address 0x5 out of bounds>, file_system=0, 
    ops=0x7fb112b85280 <util_cq_ops>, access_mode=576893104, disp=0, etype=1275068685, filetype=1275068685, info=469762048, perm=-1, error_code=0x7ffc2263897c)
    at ../../../../../src/mpi/romio/adio/common/ad_open.c:188
#13 0x00007fb15e3e9b3a in PMPI_File_open (comm=1594247784, filename=0x7ffc2262b108 " \234\005\341p\266R", amode=576948604, info=0, 
    fh=0x7fb112b85280 <util_cq_ops>) at ../../../../../src/mpi/romio/mpi-io/open.c:143
#14 0x00007fb15c97a496 in openmagic () from /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib/libnetcdf.so.19
#15 0x00007fb15c9794bd in check_file_type () from /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib/libnetcdf.so.19
#16 0x00007fb15c97821b in NC_infermodel () from /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib/libnetcdf.so.19
#17 0x00007fb15c95e837 in NC_open () from /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib/libnetcdf.so.19
#18 0x00007fb15c9849f7 in nc_open_par () from /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib/libnetcdf.so.19
#19 0x00007fb15f5ee5c0 in ex_open_par_int () from /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib/libexodus.so.2
#20 0x0000000000401231 in main ()
```
for reference, here is the output of my `nc-config --all`:
```
bbserv:~ $ nc-config --all

This netCDF 4.9.0 has been built with the following features: 

  --cc            -> /opt/HPC/intel/oneapi/mpi/2021.7.0/bin/mpiicc
  --cflags        -> -I/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/include -I/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/include -I/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/include -I/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/include -I/opt/HPC/intel/oneapi/mpi/2021.7.0/include
  --libs          -> -L/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib -lnetcdf
  --static        -> -lpnetcdf -lm -lcurl -Wl,-rpath,/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib -L/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib -lpnetcdf -Wl,-rpath,/1/HPC/intel/oneapi/mpi/2021.7.0/lib/release -L/1/HPC/intel/oneapi/mpi/2021.7.0/lib/release -Wl,-rpath,/1/HPC/intel/oneapi/mpi/2021.7.0/lib -L/1/HPC/intel/oneapi/mpi/2021.7.0/lib -Wl,-rpath,/1/HPC/intel/oneapi/mpi/2021.7.0/libfabric/lib -L/1/HPC/intel/oneapi/mpi/2021.7.0/libfabric/lib -Wl,-rpath,/1/HPC/intel/oneapi/mkl/2022.1.0/lib/intel64 -L/1/HPC/intel/oneapi/mkl/2022.1.0/lib/intel64 -Wl,-rpath,/1/HPC/intel/oneapi/compiler/2022.2.0/linux/compiler/lib/intel64_lin -L/1/HPC/intel/oneapi/compiler/2022.2.0/linux/compiler/lib/intel64_lin -Wl,-rpath,/1/HPC/intel/oneapi/compiler/2022.2.0/linux/lib -L/1/HPC/intel/oneapi/compiler/2022.2.0/linux/lib -Wl,-rpath,/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11 -L/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11 -Wl,-rpath,/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib/gcc -L/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib/gcc -Wl,-rpath,/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib64 -L/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib64 -Wl,-rpath,/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib -L/1/host/bbserv/opt/rh/devtoolset-11/root/usr/lib -lstdc++ -Wl,-rpath,/1/HPC/intel/oneapi/mpi/2021.7.0/lib/release -Wl,-rpath,/1/HPC/intel/oneapi/mpi/2021.7.0/lib -lmpifort -lmpi -ldl -lrt -lpthread -lifport -lifcoremt -limf -lsvml -lm -lipgo -lirc -lgcc_s -lirc_s -Wl,-rpath,/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib -L/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib -lhdf5_hl -lhdf5 -Wl,-rpath,/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib -L/opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib -lz -lstdc++ 

  --has-c++       -> no
  --cxx           -> 

  --has-c++4      -> no
  --cxx4          -> 

  --has-fortran   -> no
  --has-dap       -> no
  --has-dap2      -> no
  --has-dap4      -> no
  --has-nc2       -> yes
  --has-nc4       -> yes
  --has-hdf5      -> yes
  --has-hdf4      -> no
  --has-logging   -> no
  --has-pnetcdf   -> yes
  --has-szlib     -> no
  --has-cdf5      -> yes
  --has-parallel4 -> yes
  --has-parallel  -> yes
  --has-nczarr    -> yes
  --has-zstd      -> no
  --has-benchmarks -> no

  --prefix        -> /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64
  --includedir    -> /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/include
  --libdir        -> /opt/HPC/petsc/main/bbserv-intel2022.2.0-impi-2021.7.0-g64/lib
  --version       -> netCDF 4.9.0
```

I _think_ that all pnetcdf tests are OK. I can investigate further if necessary.
Any idea? Does the BT help figuring out of this is an exodus, pnetcdf, or netcdf issue?

**Comment by gsjaardema** [comment]
This seems to work OK on my mac system using gnu compilers.  I will try to build an intel version hopefully later today and see if that works or shows a similar issue.

**Comment by bourdin** [comment]
Same here.
It works OK with gcc 11 / MVAPICH2 under linux but fails with gcc 11 and impi. I have tried to build mvapich2 with the intel compilers but have not been successful yet. I am also trying to get builds with the AOCC compilers to find out of this is a compiler or MPI issue.

**Comment by bourdin** [comment]
FWIW, I see the same issue with AOCC compilers and intel MPI but not with AOCC compilers and mvapich2, so it seems to be an IMPI compatibility issue.

**Comment by gsjaardema** [comment]
I think this can be closed as I don't think it is a SEACAS issue, but is instead an IMPI / Intel issue
